version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis

  processor:
    build:
      context: .
      dockerfile: Dockerfile-processor
    restart: always
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis

  reporting:
    build:
      context: .
      dockerfile: Dockerfile-reporting
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
