FROM golang:1.18

ADD go.mod /app/
ADD go.sum /app/

ADD . /app/

WORKDIR /app

RUN go mod download

WORKDIR /app/cmd/reporting

RUN CGO_ENABLED=0 GOOS=linux go build -o /reporting

EXPOSE 8082

CMD ["/reporting"]
